DROP TABLE Conference CASCADE CONSTRAINTS;
DROP TABLE Team CASCADE CONSTRAINTS;
DROP TABLE Player CASCADE CONSTRAINTS;
DROP TABLE Ranking CASCADE CONSTRAINTS;
DROP TABLE Owner CASCADE CONSTRAINTS;
DROP TABLE Schedule CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE StaffRole CASCADE CONSTRAINTS;
DROP TABLE Off_Stats CASCADE CONSTRAINTS;
DROP TABLE D_Stats CASCADE CONSTRAINTS;
DROP TABLE K_Stats CASCADE CONSTRAINTS;


CREATE TABLE Conference
(Cname CHAR(9),
numTeams  NUMBER(2),
CONSTRAINT Conference_Cname_pk PRIMARY KEY(Cname));

CREATE TABLE Team
(TName VARCHAR2(20),
Conference CHAR(9),
SName VARCHAR2(20),
Street VARCHAR2(20),
City VARCHAR2(10),
State CHAR(2),
Zip CHAR(5),
CONSTRAINT Team_TName_pk PRIMARY KEY(TName),
CONSTRAINT Team_SName_uk UNIQUE(SName),
CONSTRAINT Team_Conference_fk FOREIGN KEY(Conference) REFERENCES Conference(Cname));

CREATE TABLE Player
(PlayerID NUMBER(6),
Fname VARCHAR2(10),
Lname  VARCHAR2(10),
Position CHAR(2),
TID VARCHAR2(20),
CONSTRAINT Player_PlayerID_pk PRIMARY KEY(PlayerID),
CONSTRAINT Player_TID_fk FOREIGN KEY(TID) REFERENCES Team(TName));

CREATE TABLE Ranking
(TID VARCHAR2(20),
WeekNum CHAR(2),
O_Rank NUMBER(2),
D_Rank NUMBER(2),
P_Rank NUMBER(2),
Wins NUMBER(2),
Loss NUMBER(2),
CONSTRAINT Ranking_WeekNum_TID_pk PRIMARY KEY(TID, WeekNum),
CONSTRAINT Ranking_TID_fk FOREIGN KEY(TID) REFERENCES Team(TName));

CREATE TABLE Owner
(Fname VARCHAR2(10),
Lname VARCHAR2(10),
Age NUMBER(2),
TID VARCHAR2(20),
YearsOwned NUMBER(2),
CONSTRAINT Owner_Fname_Lname_pk PRIMARY KEY(Fname, Lname),
CONSTRAINT Owner_TID_fk FOREIGN KEY(TID) REFERENCES Team(TName));


CREATE TABLE Schedule
(TID VARCHAR2(20),
WeekNum NUMBER(2),
Opp VARCHAR2(20),
Home_Away CHAR(4),
Result VARCHAR2(5),
CONSTRAINT Schedule_WeekNum_TID_pk PRIMARY KEY(TID, WeekNum),
CONSTRAINT Schedule_TID_fk FOREIGN KEY(TID) REFERENCES Team(TName));

CREATE TABLE Staff
(SID NUMBER(5),
Fname VARCHAR2(10),
Lname VARCHAR2(10),
TID VARCHAR2(20),
gmName VARCHAR2(10),
CONSTRAINT Staff_SID_pk PRIMARY KEY(SID),
CONSTRAINT Staff_TID_fk FOREIGN KEY(TID) REFERENCES Team(TName));


CREATE TABLE StaffRole
(SID NUMBER(5),
Position VARCHAR2(20),
CONSTRAINT StaffRole_SID_position_pk PRIMARY KEY(SID, Position),
CONSTRAINT StaffRole_SID_fk FOREIGN KEY(SID) REFERENCES Staff(SID));

CREATE TABLE Off_Stats
(PID NUMBER(6), 
Weeknum NUMBER(2),
Proj_Pts NUMBER(5),
Actual_Pts NUMBER(5),
Pass_yds NUMBER(3),
P_40_Yd NUMBER(3),
P_40_Td NUMBER(3),
Int NUMBER(3),
Trgts NUMBER(3),
Rec NUMBER(3),
Rec_40_Yd NUMBER(3),
Rec_40_Td NUMBER(3),
Fum NUMBER(3),
Rec_TD NUMBER(3),
Two_Pt NUMBER(3),
Rush_Att NUMBER(3),
Rush_yd NUMBER(3),
Rush_Td NUMBER(3),
R_40_Yd NUMBER(3),
R_40_Td NUMBER(3),
CONSTRAINT Off_Stats_Weeknum_PID_pk PRIMARY KEY(PID, Weeknum),
CONSTRAINT Off_Stats_PID_fk FOREIGN KEY(PID) REFERENCES Player(PlayerID));

CREATE TABLE D_Stats
(PID NUMBER(6),
Weeknum NUMBER(2),
Proj_Pts NUMBER(5),
Actual_Pts NUMBER(5),
Pts_Allow NUMBER(3),
Sacks NUMBER(3),
Safety NUMBER(3),
Int NUMBER(3),
Fum_Rec NUMBER(3),
Def_Td NUMBER(3),
Ret_Td NUMBER(3),
Blk_Kick NUMBER(3),
CONSTRAINT D_Stats_Weeknum_PID_pk PRIMARY KEY(PID, Weeknum),
CONSTRAINT D_Stats_PID_fk FOREIGN KEY(PID) REFERENCES Player(PlayerID));

CREATE TABLE K_Stats
(PID NUMBER(6),
Weeknum NUMBER(2),
Proj_Pts NUMBER(5),
Actual_Pts NUMBER(5),
Zero_19 NUMBER(3),
Twenty_29 NUMBER(3),
Thirty_39 NUMBER(3),
Forty_49 NUMBER(3),
Fifty_Plus NUMBER(3),
PAT NUMBER(3),
CONSTRAINT K_Stats_PID_Weeknum_pk PRIMARY KEY(PID, Weeknum),
CONSTRAINT K_Stats_PID_fk FOREIGN KEY(PID) REFERENCES Player(PlayerID));


DESCRIBE Conference;
DESCRIBE Team;
DESCRIBE Player;
DESCRIBE Ranking;
DESCRIBE Owner;
DESCRIBE Schedule;
DESCRIBE Staff;
DESCRIBE StaffRole;
DESCRIBE Off_Stats;
DESCRIBE D_Stats;
DESCRIBE K_Stats;



















 











 